import ast
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import sys
import tempfile

root=Path.cwd()
def edit(path, replacements):
    p=Path(path);s=p.read_text()
    for old,new in replacements:
        assert old in s,(path,old)
        s=s.replace(old,new)
    p.write_text(s)

# The four external/root-boundary methods already exist in MaterializerTests.
# Replay appended identical copies to the unrelated ArchivedReplayTests class.
p=Path('tools/native_retirement_materializer_test.py');s=p.read_text();tree=ast.parse(s)
classes={c.name:{f.name:f for f in c.body if isinstance(f,ast.FunctionDef)}
         for c in tree.body if isinstance(c,ast.ClassDef)}
a,b=classes['MaterializerTests'],classes['ArchivedReplayTests']
spans=[]
for name in sorted(a.keys()&b.keys()-{'setUp'}):
    assert ast.dump(a[name])==ast.dump(b[name]),name
    spans.append((b[name].lineno-1,b[name].end_lineno))
assert len(spans)==4
lines=s.splitlines(keepends=True)
for start,end in sorted(spans,reverse=True):
    del lines[start:end]
s=''.join(lines)
s=re.sub(r'\n{4,}(?=if __name__)', '\n\n\n',s)
p.write_text(s)

edit('tools/native_retirement_contract.py',[
    ('FULL_SUBJECT_COUNT = 402','FULL_SUBJECT_COUNT = 403'),
    ('FULL_ROW_COUNT = 77184','FULL_ROW_COUNT = 77376'),
    ('manifest.get("inputs") == "548"','manifest.get("inputs") == "549"'),
    ('full 402-subject inventory','full 403-subject inventory')])
edit('tools/native_retirement_contract_test.py',[
    ('548','549'),('"subjects": "402"','"subjects": "403"'),
    ('{"subject": 402','{"subject": 403')])
edit('tests/ci_tools_test.py',[
    ('"subject": 402','"subject": 403'),
    ('"supported-object-zero-fallback": 396','"supported-object-zero-fallback": 397'),
    ('self.assertNotIn("397 supported-object subjects", prose)',
     'self.assertNotIn("396 supported-object subjects", prose)')])
edit('tools/native_retirement_census.c',[
    ('input_count == 548 && subject_count == 402 && groups == 19296',
     'input_count == 549 && subject_count == 403 && groups == 19344'),
    ('== 77184;', '== 77376;')])
edit('docs/native-retirement-census.md',[
    ('548','549'),('402','403'),('396','397'),('77,184','77,376')])
p=Path('docs/native-retirement-census.md');s=p.read_text()
anchor='Merging a contract change is the maintainer approval record.\n'
assert anchor in s
s=s.replace(anchor,anchor+'\nThe September 16, 2026 rebase retains the `tests/issue36_target_wchar.c`\nsubject already admitted on `main` by #694. It adds that subject to #645\'s\noriginal 548-input/402-subject census rather than dropping it: the integrated\nprofile has 549 inputs, 403 subjects, 19,344 groups and 77,376 rows. The original\nfixture bytes, the 192-row historical gap ledger, and the 341-entry\napplicability projection remain unchanged.\n')
p.write_text(s)

# Refresh the merged support-file bytes, never an obligation or subject.
p=Path('docs/native-retirement-support-v1.tsv');lines=p.read_text().splitlines()
for i,line in enumerate(lines):
    fields=line.split('\t')
    if fields[0]=='tests/ci_tools_test.py':
        assert fields[1:3]==['support-file','dependency-only']
        data=Path(fields[0]).read_bytes()
        fields[3:]=[str(len(data)),hashlib.sha256(data).hexdigest()]
        lines[i]='\t'.join(fields)
p.write_text('\n'.join(lines)+'\n')
support_pin=hashlib.sha256(p.read_bytes()).hexdigest()
for path in ('tools/native_retirement_materializer.py','tools/native_retirement_materializer_test.py',
             'tools/native_retirement_contract.py'):
    edit(path,[('24ae23cff2ab5bd6ff46304a878ed4dc3e5d639422751de93ea74dabde7e437e',support_pin)])

# Only repository-owned records change. External pins and generated bytes do not.
p=Path('docs/native-retirement-dependencies-v1.json');s=p.read_text();changed=[]
def refresh(m):
    row=json.loads(m[2])
    if not row.get('source','').startswith('src/'):
        return m[0]
    data=Path(row['source']).read_bytes();size=len(data);digest=hashlib.sha256(data).hexdigest()
    if (size,digest)!=(row['bytes'],row['sha256']):
        changed.append(row['source']);row['bytes']=size;row['sha256']=digest
    return m[1]+json.dumps(row)+m[3]
s=re.sub(r'(?m)^(\s*)(\{"source": [^\n]+?\})(,?)$',refresh,s)
p.write_text(s)

# Materialize actual bytes to derive all four independent fixed trust anchors.
sys.path.insert(0,str(root/'tools'))
import native_retirement_materializer as materializer
assert materializer.SUPPORT_CONTRACT_SHA256==support_pin
with tempfile.TemporaryDirectory() as d:
    out=Path(d).resolve()/'closure'
    receipt=materializer.materialize_file(root/p,root,out)
    pins={
      'f45cd452eb02b56b06f91db70064c735ab55810ad8fdc690e2a6be7d3c92a562':hashlib.sha256(p.read_bytes()).hexdigest(),
      '9102b77674285f04e4d4fd781d80f273051674a9f911dab2c868adcf5922523c':hashlib.sha256((out/'dependency-manifest.json').read_bytes()).hexdigest(),
      'f370491368b6f7b013619f412640126454681043f27a2b9fb9f92f2465555a3d':receipt['project_include_sha256'],
      '60953f97c4968a4888863ebd0ab72dc17be550cb2d7f70b94c71455d8d6d9344':receipt['ledger_sha256'],
    }
for path in ('tools/native_retirement_census.c','tools/native_retirement_contract.py','docs/native-retirement-census.md'):
    edit(path,list(pins.items()))
print(json.dumps({'support_pin':support_pin,'dependency_pins':pins,'refreshed_repo_sources':changed},sort_keys=True))

# main expanded the SIMD fixture without changing its registered target scope.
# Preserve that reviewed input and rebind only its two existing iOS entries.
p=Path('docs/native-retirement-applicability-v1.tsv');s=p.read_text()
old='f03b3b648b17707d22312553c9320a1310c8afb94a24357924ca0a046261b333'
new=hashlib.sha256(Path('tests/basic_c_simd_translate.c').read_bytes()).hexdigest()
assert s.count(old)==2
s=s.replace(old,new);p.write_text(s)
app_pin=hashlib.sha256(p.read_bytes()).hexdigest()
for path in ('tools/native_retirement_census.c','tools/native_retirement_contract.py'):
    edit(path,[('6edc25e9b09884bf7c1f2e4711909120667503e22e84025316d9cd94eb77b4ad',app_pin)])
edit('docs/native-retirement-census.md',[
    ('fixture bytes, the 192-row historical gap ledger, and the 341-entry\napplicability projection remain unchanged.',
     '192-row historical gap ledger and all 341 applicability classifications remain\nunchanged. The rebase makes no fixture edits: it retains main\'s expanded SIMD\nfixture and refreshes that input\'s two existing iOS applicability hashes.')])
print(json.dumps({'applicability_pin':app_pin,'simd_fixture_sha256':new},sort_keys=True))

# Regression: a pinned applicability record must also match the real fixture,
# not only the pinned ledger's own byte identity.
edit('tools/native_retirement_contract_test.py',[(
    '            self.assertTrue(record["fixture_sha256"])',
    '            fixture_path = ledger_path.parents[1] / record["fixture"]\n'
    '            self.assertEqual(sha(fixture_path.read_bytes()), record["fixture_sha256"])')])
