on: [push]

env:
  BUSTER_CI: 'ON'

jobs:
  test_controller:
    strategy:
      matrix:
        runner: [zen5-linux]
    name: All [${{matrix.runner}}]
    uses: ./.forgejo/workflows/unix.yml
    with:
      runner: ${{ matrix.runner }}
