unsigned f0(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 0u; return s; }
unsigned f1(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 1u; return s; }
unsigned f2(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 2u; return s; }
unsigned f3(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 3u; return s; }
unsigned f4(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 4u; return s; }
unsigned f5(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 5u; return s; }
unsigned f6(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 6u; return s; }
unsigned f7(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 7u; return s; }
unsigned f8(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 8u; return s; }
unsigned f9(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 9u; return s; }
unsigned f10(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 10u; return s; }
unsigned f11(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 11u; return s; }
unsigned f12(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 12u; return s; }
unsigned f13(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 13u; return s; }
unsigned f14(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 14u; return s; }
unsigned f15(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 15u; return s; }
unsigned f16(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 16u; return s; }
unsigned f17(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 17u; return s; }
unsigned f18(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 18u; return s; }
unsigned f19(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 19u; return s; }
unsigned f20(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 20u; return s; }
unsigned f21(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 21u; return s; }
unsigned f22(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 22u; return s; }
unsigned f23(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 23u; return s; }
unsigned f24(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 24u; return s; }
unsigned f25(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 25u; return s; }
unsigned f26(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 26u; return s; }
unsigned f27(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 27u; return s; }
unsigned f28(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 28u; return s; }
unsigned f29(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 29u; return s; }
unsigned f30(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 30u; return s; }
unsigned f31(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 31u; return s; }
unsigned f32(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 32u; return s; }
unsigned f33(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 33u; return s; }
unsigned f34(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 34u; return s; }
unsigned f35(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 35u; return s; }
unsigned f36(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 36u; return s; }
unsigned f37(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 37u; return s; }
unsigned f38(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 38u; return s; }
unsigned f39(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 39u; return s; }
unsigned f40(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 40u; return s; }
unsigned f41(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 41u; return s; }
unsigned f42(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 42u; return s; }
unsigned f43(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 43u; return s; }
unsigned f44(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 44u; return s; }
unsigned f45(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 45u; return s; }
unsigned f46(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 46u; return s; }
unsigned f47(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 47u; return s; }
unsigned f48(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 48u; return s; }
unsigned f49(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 49u; return s; }
unsigned f50(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 50u; return s; }
unsigned f51(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 51u; return s; }
unsigned f52(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 52u; return s; }
unsigned f53(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 53u; return s; }
unsigned f54(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 54u; return s; }
unsigned f55(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 55u; return s; }
unsigned f56(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 56u; return s; }
unsigned f57(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 57u; return s; }
unsigned f58(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 58u; return s; }
unsigned f59(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 59u; return s; }
unsigned f60(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 60u; return s; }
unsigned f61(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 61u; return s; }
unsigned f62(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 62u; return s; }
unsigned f63(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 63u; return s; }
unsigned f64(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 64u; return s; }
unsigned f65(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 65u; return s; }
unsigned f66(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 66u; return s; }
unsigned f67(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 67u; return s; }
unsigned f68(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 68u; return s; }
unsigned f69(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 69u; return s; }
unsigned f70(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 70u; return s; }
unsigned f71(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 71u; return s; }
unsigned f72(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 72u; return s; }
unsigned f73(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 73u; return s; }
unsigned f74(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 74u; return s; }
unsigned f75(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 75u; return s; }
unsigned f76(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 76u; return s; }
unsigned f77(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 77u; return s; }
unsigned f78(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 78u; return s; }
unsigned f79(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 79u; return s; }
unsigned f80(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 80u; return s; }
unsigned f81(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 81u; return s; }
unsigned f82(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 82u; return s; }
unsigned f83(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 83u; return s; }
unsigned f84(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 84u; return s; }
unsigned f85(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 85u; return s; }
unsigned f86(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 86u; return s; }
unsigned f87(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 87u; return s; }
unsigned f88(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 88u; return s; }
unsigned f89(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 89u; return s; }
unsigned f90(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 90u; return s; }
unsigned f91(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 91u; return s; }
unsigned f92(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 92u; return s; }
unsigned f93(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 93u; return s; }
unsigned f94(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 94u; return s; }
unsigned f95(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 95u; return s; }
unsigned f96(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 96u; return s; }
unsigned f97(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 97u; return s; }
unsigned f98(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 98u; return s; }
unsigned f99(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 99u; return s; }
unsigned f100(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 100u; return s; }
unsigned f101(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 101u; return s; }
unsigned f102(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 102u; return s; }
unsigned f103(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 103u; return s; }
unsigned f104(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 104u; return s; }
unsigned f105(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 105u; return s; }
unsigned f106(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 106u; return s; }
unsigned f107(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 107u; return s; }
unsigned f108(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 108u; return s; }
unsigned f109(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 109u; return s; }
unsigned f110(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 110u; return s; }
unsigned f111(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 111u; return s; }
unsigned f112(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 112u; return s; }
unsigned f113(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 113u; return s; }
unsigned f114(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 114u; return s; }
unsigned f115(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 115u; return s; }
unsigned f116(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 116u; return s; }
unsigned f117(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 117u; return s; }
unsigned f118(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 118u; return s; }
unsigned f119(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 119u; return s; }
unsigned f120(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 120u; return s; }
unsigned f121(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 121u; return s; }
unsigned f122(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 122u; return s; }
unsigned f123(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 123u; return s; }
unsigned f124(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 124u; return s; }
unsigned f125(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 125u; return s; }
unsigned f126(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 126u; return s; }
unsigned f127(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 127u; return s; }
unsigned f128(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 128u; return s; }
unsigned f129(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 129u; return s; }
unsigned f130(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 130u; return s; }
unsigned f131(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 131u; return s; }
unsigned f132(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 132u; return s; }
unsigned f133(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 133u; return s; }
unsigned f134(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 134u; return s; }
unsigned f135(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 135u; return s; }
unsigned f136(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 136u; return s; }
unsigned f137(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 137u; return s; }
unsigned f138(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 138u; return s; }
unsigned f139(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 139u; return s; }
unsigned f140(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 140u; return s; }
unsigned f141(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 141u; return s; }
unsigned f142(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 142u; return s; }
unsigned f143(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 143u; return s; }
unsigned f144(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 144u; return s; }
unsigned f145(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 145u; return s; }
unsigned f146(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 146u; return s; }
unsigned f147(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 147u; return s; }
unsigned f148(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 148u; return s; }
unsigned f149(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 149u; return s; }
unsigned f150(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 150u; return s; }
unsigned f151(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 151u; return s; }
unsigned f152(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 152u; return s; }
unsigned f153(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 153u; return s; }
unsigned f154(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 154u; return s; }
unsigned f155(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 155u; return s; }
unsigned f156(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 156u; return s; }
unsigned f157(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 157u; return s; }
unsigned f158(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 158u; return s; }
unsigned f159(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 159u; return s; }
unsigned f160(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 160u; return s; }
unsigned f161(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 161u; return s; }
unsigned f162(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 162u; return s; }
unsigned f163(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 163u; return s; }
unsigned f164(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 164u; return s; }
unsigned f165(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 165u; return s; }
unsigned f166(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 166u; return s; }
unsigned f167(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 167u; return s; }
unsigned f168(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 168u; return s; }
unsigned f169(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 169u; return s; }
unsigned f170(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 170u; return s; }
unsigned f171(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 171u; return s; }
unsigned f172(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 172u; return s; }
unsigned f173(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 173u; return s; }
unsigned f174(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 174u; return s; }
unsigned f175(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 175u; return s; }
unsigned f176(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 176u; return s; }
unsigned f177(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 177u; return s; }
unsigned f178(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 178u; return s; }
unsigned f179(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 179u; return s; }
unsigned f180(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 180u; return s; }
unsigned f181(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 181u; return s; }
unsigned f182(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 182u; return s; }
unsigned f183(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 183u; return s; }
unsigned f184(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 184u; return s; }
unsigned f185(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 185u; return s; }
unsigned f186(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 186u; return s; }
unsigned f187(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 187u; return s; }
unsigned f188(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 188u; return s; }
unsigned f189(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 189u; return s; }
unsigned f190(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 190u; return s; }
unsigned f191(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 191u; return s; }
unsigned f192(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 192u; return s; }
unsigned f193(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 193u; return s; }
unsigned f194(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 194u; return s; }
unsigned f195(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 195u; return s; }
unsigned f196(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 196u; return s; }
unsigned f197(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 197u; return s; }
unsigned f198(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 198u; return s; }
unsigned f199(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 199u; return s; }
unsigned f200(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 200u; return s; }
unsigned f201(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 201u; return s; }
unsigned f202(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 202u; return s; }
unsigned f203(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 203u; return s; }
unsigned f204(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 204u; return s; }
unsigned f205(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 205u; return s; }
unsigned f206(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 206u; return s; }
unsigned f207(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 207u; return s; }
unsigned f208(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 208u; return s; }
unsigned f209(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 209u; return s; }
unsigned f210(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 210u; return s; }
unsigned f211(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 211u; return s; }
unsigned f212(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 212u; return s; }
unsigned f213(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 213u; return s; }
unsigned f214(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 214u; return s; }
unsigned f215(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 215u; return s; }
unsigned f216(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 216u; return s; }
unsigned f217(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 217u; return s; }
unsigned f218(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 218u; return s; }
unsigned f219(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 219u; return s; }
unsigned f220(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 220u; return s; }
unsigned f221(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 221u; return s; }
unsigned f222(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 222u; return s; }
unsigned f223(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 223u; return s; }
unsigned f224(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 224u; return s; }
unsigned f225(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 9u + 225u; return s; }
unsigned f226(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 10u + 226u; return s; }
unsigned f227(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 11u + 227u; return s; }
unsigned f228(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 12u + 228u; return s; }
unsigned f229(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 13u + 229u; return s; }
unsigned f230(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 14u + 230u; return s; }
unsigned f231(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 15u + 231u; return s; }
unsigned f232(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 16u + 232u; return s; }
unsigned f233(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 17u + 233u; return s; }
unsigned f234(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 18u + 234u; return s; }
unsigned f235(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 19u + 235u; return s; }
unsigned f236(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 20u + 236u; return s; }
unsigned f237(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 21u + 237u; return s; }
unsigned f238(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 22u + 238u; return s; }
unsigned f239(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 23u + 239u; return s; }
unsigned f240(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 24u + 240u; return s; }
unsigned f241(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 25u + 241u; return s; }
unsigned f242(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 26u + 242u; return s; }
unsigned f243(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 27u + 243u; return s; }
unsigned f244(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 28u + 244u; return s; }
unsigned f245(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 29u + 245u; return s; }
unsigned f246(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 30u + 246u; return s; }
unsigned f247(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 31u + 247u; return s; }
unsigned f248(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 1u + 248u; return s; }
unsigned f249(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 2u + 249u; return s; }
unsigned f250(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 3u + 250u; return s; }
unsigned f251(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 4u + 251u; return s; }
unsigned f252(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 5u + 252u; return s; }
unsigned f253(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 6u + 253u; return s; }
unsigned f254(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 7u + 254u; return s; }
unsigned f255(const unsigned *a, unsigned n, unsigned salt) { unsigned s = salt; for (unsigned i=0; i<n; i+=1) s += a[i] * 8u + 255u; return s; }