#pragma once

#include <buster/lib.h>

ENUM_T(CpuArch, u8,
    CPU_ARCH_X86_64,
    CPU_ARCH_AARCH64,
);

ENUM_T(OperatingSystem, u8, 
    OPERATING_SYSTEM_LINUX,
    OPERATING_SYSTEM_MACOS,
    OPERATING_SYSTEM_WINDOWS,
    OPERATING_SYSTEM_UEFI,
    OPERATING_SYSTEM_ANDROID,
    OPERATING_SYSTEM_IOS,
    OPERATING_SYSTEM_FREESTANDING,
);

ENUM_T(CpuModel, u8, 
    CPU_MODEL_ERROR,
    CPU_MODEL_BASELINE,
    CPU_MODEL_NATIVE,
    CPU_MODEL_AMD_I486,
    CPU_MODEL_AMD_PENTIUM,
    CPU_MODEL_AMD_K6,
    CPU_MODEL_AMD_K6_2,
    CPU_MODEL_AMD_K6_3,
    CPU_MODEL_AMD_GEODE,
    CPU_MODEL_AMD_ATHLON,
    CPU_MODEL_AMD_ATHLON_XP,
    CPU_MODEL_AMD_K8,
    CPU_MODEL_AMD_K8_SSE3,
    CPU_MODEL_AMD_AMD_FAMILY_10,
    CPU_MODEL_AMD_BT_1,
    CPU_MODEL_AMD_BT_2,
    CPU_MODEL_AMD_BD_1,
    CPU_MODEL_AMD_BD_2,
    CPU_MODEL_AMD_BD_3,
    CPU_MODEL_AMD_BD_4,
    CPU_MODEL_AMD_ZEN_1,
    CPU_MODEL_AMD_ZEN_2,
    CPU_MODEL_AMD_ZEN_3,
    CPU_MODEL_AMD_ZEN_4,
    CPU_MODEL_AMD_ZEN_5,

    CPU_MODEL_INTEL_CORE_2,
    CPU_MODEL_INTEL_PENRYN,
    CPU_MODEL_INTEL_NEHALEM,
    CPU_MODEL_INTEL_WESTMERE,
    CPU_MODEL_INTEL_SANDY_BRIDGE,
    CPU_MODEL_INTEL_IVY_BRIDGE,
    CPU_MODEL_INTEL_HASWELL,
    CPU_MODEL_INTEL_BROADWELL,
    CPU_MODEL_INTEL_SKYLAKE,
    CPU_MODEL_INTEL_SKYLAKE_AVX512,
    CPU_MODEL_INTEL_ROCKETLAKE,
    CPU_MODEL_INTEL_COOPERLAKE,
    CPU_MODEL_INTEL_CASCADELAKE,
    CPU_MODEL_INTEL_CANNONLAKE,
    CPU_MODEL_INTEL_ICELAKE_CLIENT,
    CPU_MODEL_INTEL_TIGERLAKE,
    CPU_MODEL_INTEL_ALDERLAKE,
    CPU_MODEL_INTEL_RAPTORLAKE,
    CPU_MODEL_INTEL_METEORLAKE,
    CPU_MODEL_INTEL_GRACEMONT,
    CPU_MODEL_INTEL_ARROWLAKE,
    CPU_MODEL_INTEL_ARROWLAKE_S,
    CPU_MODEL_INTEL_LUNARLAKE,
    CPU_MODEL_INTEL_PANTHERLAKE,
    CPU_MODEL_INTEL_ICELAKE_SERVER,
    CPU_MODEL_INTEL_EMERALD_RAPIDS,
    CPU_MODEL_INTEL_SAPPHIRE_RAPIDS,
    CPU_MODEL_INTEL_GRANITE_RAPIDS,
    CPU_MODEL_INTEL_GRANITE_RAPIDS_D,
    CPU_MODEL_INTEL_BONNELL,
    CPU_MODEL_INTEL_SILVERMONT,
    CPU_MODEL_INTEL_GOLDMONT,
    CPU_MODEL_INTEL_GOLDMONT_PLUS,
    CPU_MODEL_INTEL_TREMONT,
    CPU_MODEL_INTEL_SIERRAFOREST,
    CPU_MODEL_INTEL_GRANDRIDGE,
    CPU_MODEL_INTEL_CLEARWATERFOREST,
    CPU_MODEL_INTEL_KNL,
    CPU_MODEL_INTEL_KNM,
    CPU_MODEL_INTEL_DIAMOND_RAPIDS,

    CPU_MODEL_A64_GENERIC,

    CPU_MODEL_A64_ARM_ARM920T,
    CPU_MODEL_A64_ARM_ARM926EJ_S,
    CPU_MODEL_A64_ARM_MPCORE,
    CPU_MODEL_A64_ARM_ARM1136J_S,
    CPU_MODEL_A64_ARM_ARM1156T2_S,
    CPU_MODEL_A64_ARM_ARM1176JZ_S,
    CPU_MODEL_A64_ARM_CORTEX_A5,
    CPU_MODEL_A64_ARM_CORTEX_A7,
    CPU_MODEL_A64_ARM_CORTEX_A8,
    CPU_MODEL_A64_ARM_CORTEX_A9,
    CPU_MODEL_A64_ARM_CORTEX_A15,
    CPU_MODEL_A64_ARM_CORTEX_A17,
    CPU_MODEL_A64_ARM_CORTEX_M0,
    CPU_MODEL_A64_ARM_CORTEX_M3,
    CPU_MODEL_A64_ARM_CORTEX_M4,
    CPU_MODEL_A64_ARM_CORTEX_M7,
    CPU_MODEL_A64_ARM_CORTEX_M23,
    CPU_MODEL_A64_ARM_CORTEX_M33,
    CPU_MODEL_A64_ARM_CORTEX_M52,
    CPU_MODEL_A64_ARM_CORTEX_M55,
    CPU_MODEL_A64_ARM_CORTEX_M85,
    CPU_MODEL_A64_ARM_CORTEX_R8,
    CPU_MODEL_A64_ARM_CORTEX_R52,
    CPU_MODEL_A64_ARM_CORTEX_R52PLUS,
    CPU_MODEL_A64_ARM_CORTEX_R82,
    CPU_MODEL_A64_ARM_CORTEX_R82AE,
    CPU_MODEL_A64_ARM_CORTEX_A34,
    CPU_MODEL_A64_ARM_CORTEX_A35,
    CPU_MODEL_A64_ARM_CORTEX_A320,
    CPU_MODEL_A64_ARM_CORTEX_A53,
    CPU_MODEL_A64_ARM_CORTEX_A55,
    CPU_MODEL_A64_ARM_CORTEX_A510,
    CPU_MODEL_A64_ARM_CORTEX_A520,
    CPU_MODEL_A64_ARM_CORTEX_A520AE,
    CPU_MODEL_A64_ARM_CORTEX_A57,
    CPU_MODEL_A64_ARM_CORTEX_A65,
    CPU_MODEL_A64_ARM_CORTEX_A65AE,
    CPU_MODEL_A64_ARM_CORTEX_A72,
    CPU_MODEL_A64_ARM_CORTEX_A73,
    CPU_MODEL_A64_ARM_CORTEX_A75,
    CPU_MODEL_A64_ARM_CORTEX_A76,
    CPU_MODEL_A64_ARM_CORTEX_A76AE,
    CPU_MODEL_A64_ARM_CORTEX_A77,
    CPU_MODEL_A64_ARM_CORTEX_A78,
    CPU_MODEL_A64_ARM_CORTEX_A78AE,
    CPU_MODEL_A64_ARM_CORTEX_A78C,
    CPU_MODEL_A64_ARM_CORTEX_A710,
    CPU_MODEL_A64_ARM_CORTEX_A715,
    CPU_MODEL_A64_ARM_CORTEX_A720,
    CPU_MODEL_A64_ARM_CORTEX_A720AE,
    CPU_MODEL_A64_ARM_CORTEX_A725,
    CPU_MODEL_A64_ARM_CORTEX_X1,
    CPU_MODEL_A64_ARM_CORTEX_X1C,
    CPU_MODEL_A64_ARM_CORTEX_X2,
    CPU_MODEL_A64_ARM_CORTEX_X3,
    CPU_MODEL_A64_ARM_CORTEX_X4,
    CPU_MODEL_A64_ARM_CORTEX_X925,
    CPU_MODEL_A64_ARM_NEOVERSE_E1,
    CPU_MODEL_A64_ARM_NEOVERSE_N1,
    CPU_MODEL_A64_ARM_NEOVERSE_N2,
    CPU_MODEL_A64_ARM_NEOVERSE_N3,
    CPU_MODEL_A64_ARM_NEOVERSE_V1,
    CPU_MODEL_A64_ARM_NEOVERSE_V2,
    CPU_MODEL_A64_ARM_NEOVERSE_V3,
    CPU_MODEL_A64_ARM_NEOVERSE_V3AE,

    CPU_MODEL_A64_ARM_XSCALE,
    CPU_MODEL_A64_ARM_SWIFT,
    CPU_MODEL_A64_ARM920T,
    CPU_MODEL_A64_APPLE_A7,
    CPU_MODEL_A64_APPLE_A8,
    CPU_MODEL_A64_APPLE_A9,
    CPU_MODEL_A64_APPLE_A10,
    CPU_MODEL_A64_APPLE_A11,
    CPU_MODEL_A64_APPLE_A12,
    CPU_MODEL_A64_APPLE_A13,
    CPU_MODEL_A64_APPLE_M1,
    CPU_MODEL_A64_APPLE_M2,
    CPU_MODEL_A64_APPLE_A17,
    CPU_MODEL_A64_APPLE_M3,
    CPU_MODEL_A64_APPLE_M4,

    CPU_MODEL_COUNT,
);

typedef u64 TargetCpuFeatures;

ENUM(TargetStringComponents,
    TARGET_CPU_ARCH,
    TARGET_OPERATING_SYSTEM,
    TARGET_CPU_MODEL,
    TARGET_STRING_COMPONENT_COUNT,
);

STRUCT(Target)
{
    CpuArch cpu_arch;
    CpuModel cpu_model;
    OperatingSystem os;
    u8 reserved[5];
    TargetCpuFeatures* cpu_features;
};

STRUCT(TargetStringSplit)
{
    OsString s[TARGET_STRING_COMPONENT_COUNT];
};

BUSTER_DECL Target target_native;

BUSTER_DECL bool cpu_is_native(CpuModel model);
BUSTER_DECL CpuModel cpu_detect_model();
BUSTER_DECL TargetStringSplit target_to_split_os_string(Target target);
BUSTER_DECL OsString target_to_string(Arena* arena, Target target);
BUSTER_DECL OsString cpu_arch_to_os_string(CpuArch arch);
BUSTER_DECL OsString operating_system_to_os_string(OperatingSystem os);
BUSTER_DECL OsString cpu_model_to_os_string(CpuModel model);

#if BUSTER_UNITY_BUILD
#include <buster/target.c>
#endif
