#!/usr/bin/env python3
"""Differentially test `ide cc` against clang on generated C programs.

Every program is generated from a seeded grammar, compiled four ways, executed,
and its observable behavior compared:

  clang -O0   the reference implementation
  clang -O2   the *control*: if the two clang builds disagree, the generated
              program is invalid (undefined or unspecified behavior) and the
              divergence is a harness/generator bug, never a compiler bug
  ide cc      the default pipeline (FAST register allocator)
  ide cc -fno-register-allocator
              the canonical stack emitter, a separate codegen path that has
              carried its own miscompiles (the W0 64-lane #UD family was
              canonical-path-only)

The observables are the process exit status and stdout.  Generated programs
print through the raw `write` syscall because printf is a silent no-op in
ide-built binaries, and every value a program computes is both written to
stdout (full width) and folded into an FNV-1a hash whose low bits become the
exit status — so a divergence is visible even when only one of the two
channels survives.

Programs are composed of independent *units* (one function each, reported as
`U<n> <value>` lines).  On a divergence the harness re-generates the same seed
as one-unit-per-program probes automatically, so the report names the exact
unit that diverges; that unit is usually a near-minimal fixture already.

Generator families, seeded from constructs this tree has historically
miscompiled (see docs/performance-audits/ and the fix commits referenced in
the family docstrings):

  enum_sizeof   sizeof inside enum-constant initializers (c86ed530) and its
                neighbours: enum constants as array bounds, case labels,
                static initializers, referencing earlier enumerators
  array_bound   sizeof-derived file-scope array bounds over struct tables
                (5b57105c), with canary globals so a mislaid neighbour is
                observable, plus function-scope and 2-D siblings
  sizeof_expr   sizeof over expression operands: promotions, shifts,
                ternaries, assignments, calls (which must stay unevaluated),
                nested sizeof (caad25e7 and the 162-shape probe campaign)
  lazy_operand  conditional/&&/|| operands in call-argument and
                compound-literal position with side effects in the condition
                and the arms, parenthesized and not (d27d790c; the
                parenthesized-condition double lowering is a known-open bug)
  union_vector  vector_size vectors in unions and locals, 64-bit lanes at 512
                bits (the W0-#UD family, a8383082), vector arguments and
                returns, over-aligned locals beside canaries

Usage (from the repository root, after `./build.sh build --config Release -t ide`):
    tools/differential_c_harness.py --count 50                  # smoke
    tools/differential_c_harness.py --count 2000 --jobs 16      # a real run
    tools/differential_c_harness.py --families lazy_operand --count 200
    tools/differential_c_harness.py --isolate lazy_operand:1234 # per-unit probe
    tools/differential_c_harness.py --self-test

Results land under build/differential-c/: every divergent program's source and
a report naming the family, seed, unit, and the four raw observations.
Categories are kept apart because they mean different things: `behavior` is a
wrong-code bug, `rejects` is valid code ide cc refuses, `ide-crash` is a
compiler crash, and `generator` is the harness's own bug (clang disagreed with
itself).
"""

import argparse
import concurrent.futures
import os
import random
import shutil
import subprocess
import sys
import zlib
from dataclasses import dataclass, field

REPOSITORY_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_IDE = os.path.join("build", "Release", "ide")
OUTPUT_ROOT = os.path.join("build", "differential-c")
RUN_TIMEOUT_SECONDS = 10
COMPILE_TIMEOUT_SECONDS = 60

# ---------------------------------------------------------------------------
# Program skeleton
# ---------------------------------------------------------------------------

PRELUDE = """\
// Generated by tools/differential_c_harness.py family={family} seed={seed}
// Compile with clang and `ide cc`; the program prints every observed value
// with the raw write syscall (printf is a silent no-op under ide-built
// binaries) and exits with the low bits of an FNV-1a hash over them.
typedef unsigned long long u64;
long write(int, const void*, unsigned long);

static u64 hash_state = 1469598103934665603ull;

static void sink(u64 value)
{{
    hash_state = (hash_state ^ value) * 1099511628211ull;
}}

static void emit_text(const char* text, unsigned long length)
{{
    write(1, text, length);
}}

static void emit_u64(u64 value)
{{
    char buffer[24];
    int index = 24;
    do
    {{
        index -= 1;
        buffer[index] = (char)('0' + (value % 10u));
        value /= 10u;
    }} while (value);
    emit_text(buffer + index, (unsigned long)(24 - index));
}}

static void unit_report(u64 unit, u64 value)
{{
    emit_text("U", 1);
    emit_u64(unit);
    emit_text(" ", 1);
    emit_u64(value);
    emit_text("\\n", 1);
    sink(unit);
    sink(value);
}}
"""

MAIN_TEMPLATE = """\
int main(void)
{{
{calls}\
    emit_text("H ", 2);
    emit_u64(hash_state);
    emit_text("\\n", 1);
    return (int)(hash_state & 63u);
}}
"""


@dataclass
class Unit:
    """One independent check: file-scope support text plus a body computing a u64."""

    globals_text: str
    body_text: str  # statements; must end by assigning `result`


@dataclass
class Program:
    family: str
    seed: int
    units: list

    def render(self, selected=None):
        indices = range(len(self.units)) if selected is None else selected
        pieces = [PRELUDE.format(family=self.family, seed=self.seed)]
        calls = []
        for index in indices:
            unit = self.units[index]
            if unit.globals_text:
                pieces.append(unit.globals_text)
            pieces.append(
                "static u64 unit_%d(void)\n{\n    u64 result = 0;\n%s    return result;\n}\n"
                % (index, unit.body_text)
            )
            calls.append("    unit_report(%du, unit_%d());\n" % (index, index))
        pieces.append(MAIN_TEMPLATE.format(calls="".join(calls)))
        return "\n".join(pieces)


# ---------------------------------------------------------------------------
# Shared generator vocabulary
# ---------------------------------------------------------------------------

SCALAR_TYPES = [
    # (spelling, size on LP64, is_float)
    ("unsigned char", 1, False),
    ("unsigned short", 2, False),
    ("unsigned int", 4, False),
    ("unsigned long long", 8, False),
    ("signed char", 1, False),
    ("short", 2, False),
    ("int", 4, False),
    ("long long", 8, False),
    ("float", 4, True),
    ("double", 8, True),
]


def pick_scalar(rng):
    return rng.choice(SCALAR_TYPES)


def struct_definition(rng, tag):
    """A struct with 1..4 members; returns (text, python-known lower size bound)."""
    member_count = rng.randint(1, 4)
    members = []
    for member_index in range(member_count):
        spelling, _, _ = pick_scalar(rng)
        if rng.random() < 0.3:
            members.append("    %s m%d[%d];" % (spelling, member_index, rng.randint(2, 5)))
        else:
            members.append("    %s m%d;" % (spelling, member_index))
    text = "typedef struct %s\n{\n%s\n} %s;\n" % (tag, "\n".join(members), tag)
    return text


# ---------------------------------------------------------------------------
# Family: enum_sizeof
# ---------------------------------------------------------------------------

def generate_enum_sizeof_unit(rng, unit_index):
    prefix = "eu%d" % unit_index
    globals_parts = []
    scalar_spelling, scalar_size, _ = pick_scalar(rng)
    while scalar_spelling in ("float", "double"):
        scalar_spelling, scalar_size, _ = pick_scalar(rng)
    typedef_name = "%s_T" % prefix
    globals_parts.append("typedef %s %s;\n" % (scalar_spelling, typedef_name))
    struct_tag = "%s_S" % prefix
    globals_parts.append(struct_definition(rng, struct_tag))

    # Enumerator initializers.  Shift amounts stay provably below 31 by
    # construction so the int-typed constants never overflow.
    enumerators = []
    shapes = []
    name0 = "%s_A" % prefix.upper()
    multiplier = rng.choice([1, 2, 3])
    if scalar_size * 8 * multiplier - 2 <= 30 and rng.random() < 0.7:
        shift = "sizeof(%s) * %du - 2u" % (typedef_name, 8 * multiplier)
        enumerators.append("    %s = 1 << (%s)," % (name0, shift))
        shapes.append("shift")
    else:
        enumerators.append(
            "    %s = (int)(sizeof(%s) * %du + sizeof(%s))," % (name0, typedef_name, rng.randint(1, 9), struct_tag)
        )
        shapes.append("arith")
    name1 = "%s_B" % prefix.upper()
    second = rng.choice(
        [
            "    %s = %s + (int)sizeof(%s)," % (name1, name0, typedef_name),
            "    %s = sizeof(%s) == %du ? %d : %d," % (name1, typedef_name, scalar_size, rng.randint(3, 40), rng.randint(41, 90)),
            "    %s = (int)(sizeof(%s) / sizeof(%s))," % (name1, struct_tag, typedef_name),
            "    %s = %s * 2 - (int)sizeof(char[sizeof(%s)])," % (name1, name0, typedef_name),
        ]
    )
    enumerators.append(second)
    enum_tag = "%s_E" % prefix
    globals_parts.append("enum %s\n{\n%s\n};\n" % (enum_tag, "\n".join(enumerators)))

    body = []
    body.append("    sink((u64)%s);\n" % name0)
    body.append("    sink((u64)%s);\n" % name1)
    body.append("    sink((u64)sizeof(enum %s));\n" % enum_tag)
    use = rng.randint(0, 3)
    if use == 0:
        globals_parts.append("static char %s_pad[%s > 0 ? %s : 1];\n" % (prefix, name1, name1))
        body.append("    sink((u64)sizeof(%s_pad));\n" % prefix)
    elif use == 1:
        globals_parts.append("static const int %s_table[] = { %s, %s, %s + %s };\n" % (prefix, name0, name1, name0, name1))
        body.append("    sink((u64)%s_table[0] + (u64)%s_table[1] * 3u + (u64)%s_table[2] * 7u);\n" % (prefix, prefix, prefix))
    elif use == 2:
        globals_parts.append("static volatile int %s_probe = %d;\n" % (prefix, rng.randint(0, 1)))
        body.append("    int probe = %s_probe ? (int)%s : (int)%s;\n" % (prefix, name0, name1))
        # Only one enumerator becomes a case label: two labels could fold to
        # the same value, which is a compile error in both compilers and
        # would only add generator noise.
        body.append("    switch (probe)\n    {\n")
        body.append("    case %s: sink(11u); break;\n" % name0)
        body.append("    default: sink(33u); break;\n    }\n")
    else:
        # The historically broken context beside the two that were correct:
        # the same expression as an enumerator, a static const, and a runtime
        # value must agree.
        globals_parts.append("static const int %s_stat = 1 << (sizeof(%s) * 8u - 2u);\n" % (prefix, "unsigned short"))
        globals_parts.append("enum %s_ctx { %s_CTX = 1 << (sizeof(unsigned short) * 8u - 2u) };\n" % (prefix, prefix.upper()))
        body.append("    unsigned short probe = 0;\n")
        body.append("    sink((u64)%s_stat);\n" % prefix)
        body.append("    sink((u64)%s_CTX);\n" % prefix.upper())
        body.append("    sink((u64)(1u << (sizeof(probe) * 8u - 2u)));\n")
    body.append("    result = hash_state;\n")
    return Unit("".join(globals_parts), "".join(body))


# ---------------------------------------------------------------------------
# Family: array_bound
# ---------------------------------------------------------------------------

def generate_array_bound_unit(rng, unit_index):
    prefix = "ab%d" % unit_index
    globals_parts = []
    struct_tag = "%s_Item" % prefix
    globals_parts.append(struct_definition(rng, struct_tag))
    table_length = rng.randint(2, 6)
    items = ", ".join("{0}" for _ in range(table_length))
    globals_parts.append("static %s %s_table[] = { %s };\n" % (struct_tag, prefix, items))
    extra = rng.randint(0, 3)
    element_spelling, _, element_is_float = pick_scalar(rng)
    bound = "sizeof(%s_table) / sizeof(%s_table[0]) + %d" % (prefix, prefix, extra)
    globals_parts.append("static %s %s_dep[%s];\n" % (element_spelling, prefix, bound))
    globals_parts.append("static unsigned int %s_canary = 0x%08Xu;\n" % (prefix, rng.randrange(1, 1 << 32)))
    second_form = rng.randint(0, 2)
    if second_form == 0:
        globals_parts.append("static unsigned char %s_grid[sizeof(%s_table) / sizeof(%s_table[0])][%d];\n" % (prefix, prefix, prefix, rng.randint(2, 4)))
    elif second_form == 1:
        globals_parts.append("static unsigned short %s_second[sizeof(%s_dep) / sizeof(%s_dep[0]) + 1];\n" % (prefix, prefix, prefix))
    else:
        globals_parts.append("enum { %s_LEN = sizeof(%s_table) / sizeof(%s_table[0]) };\n" % (prefix.upper(), prefix, prefix))
        globals_parts.append("static unsigned char %s_enum_sized[%s_LEN * 2 + 1];\n" % (prefix, prefix.upper()))

    body = []
    body.append("    sink((u64)sizeof(%s_table));\n" % prefix)
    body.append("    sink((u64)sizeof(%s_dep));\n" % prefix)
    body.append("    sink((u64)(sizeof(%s_dep) / sizeof(%s_dep[0])));\n" % (prefix, prefix))
    tag_value = rng.randint(1, 100)
    cast = "(%s)" % element_spelling
    body.append("    %s_dep[0] = %s%d;\n" % (prefix, cast, tag_value))
    body.append("    %s_dep[sizeof(%s_dep) / sizeof(%s_dep[0]) - 1] = %s%d;\n" % (prefix, prefix, prefix, cast, tag_value + 1))
    if element_is_float:
        body.append("    sink((u64)%s_dep[0] + (u64)%s_dep[sizeof(%s_dep) / sizeof(%s_dep[0]) - 1] * 5u);\n" % (prefix, prefix, prefix, prefix))
    else:
        body.append("    sink((u64)%s_dep[0] + (u64)%s_dep[sizeof(%s_dep) / sizeof(%s_dep[0]) - 1] * 5u);\n" % (prefix, prefix, prefix, prefix))
    body.append("    sink((u64)%s_canary);\n" % prefix)
    if second_form == 0:
        body.append("    %s_grid[0][0] = 7; %s_grid[sizeof(%s_grid) / sizeof(%s_grid[0]) - 1][0] = 9;\n" % (prefix, prefix, prefix, prefix))
        body.append("    sink((u64)sizeof(%s_grid) + %s_grid[0][0] * 100u + %s_grid[sizeof(%s_grid) / sizeof(%s_grid[0]) - 1][0]);\n" % (prefix, prefix, prefix, prefix, prefix))
    elif second_form == 1:
        body.append("    sink((u64)sizeof(%s_second));\n" % prefix)
    else:
        body.append("    sink((u64)%s_LEN);\n" % prefix.upper())
        body.append("    sink((u64)sizeof(%s_enum_sized));\n" % prefix)
    # A function-scope sibling with the same shape.
    body.append("    static %s local_table[%d];\n" % (struct_tag, table_length))
    body.append("    static unsigned char local_dep[sizeof(local_table) / sizeof(local_table[0]) + %d];\n" % extra)
    body.append("    local_dep[0] = 3; local_dep[sizeof(local_dep) - 1] = 5;\n")
    body.append("    sink((u64)sizeof(local_dep) + local_dep[0] + local_dep[sizeof(local_dep) - 1]);\n")
    body.append("    result = hash_state;\n")
    return Unit("".join(globals_parts), "".join(body))


# ---------------------------------------------------------------------------
# Family: sizeof_expr
# ---------------------------------------------------------------------------

SIZEOF_GLOBALS_TEMPLATE = """\
static char {p}_gc = 'a';
static signed char {p}_gsc = -3;
static unsigned char {p}_guc = 200;
static _Bool {p}_gb = 1;
static short {p}_gs = -7;
static unsigned short {p}_gus = 60000;
static int {p}_gi = 11;
static unsigned int {p}_gu = 12u;
static long {p}_gl = 13;
static long long {p}_gll = 14;
static unsigned long long {p}_gull = 15u;
static float {p}_gf = 2.0f;
static double {p}_gd = 3.0;
static int {p}_garr[7];
static int* {p}_gp = {p}_garr;
static char {p}_gstr[] = "sizeof";
enum {p}_Color {{ {p}_RED = 1, {p}_GREEN = 2 }};
static enum {p}_Color {p}_ge = {p}_GREEN;
static int {p}_calls;
static short {p}_scall(void)
{{
    {p}_calls += 1;
    return 1;
}}
"""

def sizeof_operand_pool(prefix):
    p = prefix
    return [
        # Promotions: narrow operands under unary and binary operators.
        "-%s_gc" % p, "+%s_gsc" % p, "~%s_guc" % p, "!%s_gb" % p,
        "-%s_gs" % p, "~%s_gus" % p, "+%s_gb" % p, "~%s_ge" % p,
        "%s_gc + %s_gc" % (p, p), "%s_gs + %s_gs" % (p, p),
        "%s_gb + %s_gb" % (p, p), "%s_guc * %s_gsc" % (p, p),
        "%s_gc + %s_gl" % (p, p), "%s_gs + %s_gd" % (p, p),
        "%s_gu + %s_gll" % (p, p), "%s_gf + %s_gc" % (p, p),
        # Shifts: the result type is the promoted left operand alone.
        "%s_gc << 1" % p, "%s_gs << %s_gll" % (p, p), "%s_gull >> %s_gc" % (p, p),
        "%s_gus << 2" % p,
        # Assignments: the result type is the (unpromoted) left operand.
        "%s_gc = 100" % p, "%s_gs += %s_gll" % (p, p), "%s_guc *= 2" % p,
        "%s_gb = 0" % p,
        # Ternaries over same and mixed arms.
        "%s_gb ? %s_gc : %s_gc" % (p, p, p),
        "%s_gb ? %s_gs : %s_gi" % (p, p, p),
        "%s_gb ? %s_gf : %s_gd" % (p, p, p),
        "%s_gi ? %s_guc : %s_gsc" % (p, p, p),
        # Comma: the right operand decides.
        "%s_gi, %s_gc" % (p, p), "%s_gd, %s_gb" % (p, p),
        # Nested sizeof and mixed arithmetic over it.
        "sizeof(%s_gc) + %s_gi" % (p, p), "sizeof %s_gd" % p,
        "%s_gi + (int)sizeof(%s_garr)" % (p, p),
        # Arrays, pointers, strings, casts, compound literals.
        "%s_garr" % p, "*%s_gp" % p, "%s_garr[2]" % p, "&%s_gi" % p,
        "\"literal\"", "(char)%s_gi" % p, "(unsigned short)(%s_gll + 1)" % p,
        "(int[3]){1, 2, 3}", "(struct { char a; long long b; }){0}",
        # Calls in unevaluated context: the call must not run.
        "%s_scall()" % p, "%s_scall() + %s_gc" % (p, p),
        "%s_gb ? %s_scall() : %s_scall()" % (p, p, p),
    ]


def generate_sizeof_expr_unit(rng, unit_index):
    prefix = "sz%d" % unit_index
    globals_text = SIZEOF_GLOBALS_TEMPLATE.format(p=prefix)
    pool = sizeof_operand_pool(prefix)
    rng.shuffle(pool)
    picked = pool[: rng.randint(6, 12)]
    body = []
    body.append("    %s_calls = 0;\n" % prefix)
    for operand in picked:
        body.append("    sink((u64)sizeof(%s));\n" % operand)
    # The side-effect observation: no sizeof operand above may have executed.
    body.append("    sink((u64)%s_calls * 1000u + 500u);\n" % prefix)
    # And the same call evaluated for real exactly once, as the control.
    body.append("    sink((u64)%s_scall());\n" % prefix)
    body.append("    sink((u64)%s_calls);\n" % prefix)
    body.append("    result = hash_state;\n")
    return Unit(globals_text, "".join(body))


# ---------------------------------------------------------------------------
# Family: lazy_operand
# ---------------------------------------------------------------------------

LAZY_GLOBALS_TEMPLATE = """\
static int {p}_calls;
static int {p}_conds;
static int {p}_make(int payload)
{{
    {p}_calls += 1;
    return payload;
}}
static int {p}_cond(int value)
{{
    {p}_conds += 1;
    return value;
}}
static int {p}_take(int value)
{{
    return value;
}}
static int {p}_take_two(int first, int second)
{{
    return first * 100 + second;
}}
typedef struct {p}_Pair
{{
    int a;
    int b;
}} {p}_Pair;
"""


def lazy_control_expression(rng, prefix, mask_expression):
    """A control expression with recorded side effects; returns (text, kind)."""
    p = prefix
    condition_kind = rng.randint(0, 3)
    if condition_kind == 0:
        condition = mask_expression
    elif condition_kind == 1:
        condition = "%s_conds++ ? %s : %s" % (p, mask_expression, mask_expression)
        condition = "(%s)" % condition
    elif condition_kind == 2:
        condition = "%s_cond(%s)" % (p, mask_expression)
    else:
        # The known-open shape has the increment directly in the condition of
        # a (possibly parenthesized) control expression.
        condition = "%s_conds++ + %s" % (p, mask_expression)
    operator_kind = rng.randint(0, 2)
    if operator_kind == 0:
        text = "%s ? %s_make(3) : 0" % (condition, p)
    elif operator_kind == 1:
        text = "%s && %s_make(1)" % (condition, p)
    else:
        text = "%s || %s_make(1)" % (condition, p)
    parenthesization = rng.randint(0, 2)
    for _ in range(parenthesization):
        text = "(%s)" % text
    return text, condition_kind, operator_kind, parenthesization


def generate_lazy_operand_unit(rng, unit_index):
    prefix = "lz%d" % unit_index
    globals_text = LAZY_GLOBALS_TEMPLATE.format(p=prefix)
    p = prefix
    body = []
    body.append("    %s_calls = 0;\n" % p)
    body.append("    %s_conds = 0;\n" % p)
    check_count = rng.randint(3, 6)
    for check_index in range(check_count):
        mask = rng.randint(0, 1)
        expression, _, _, _ = lazy_control_expression(rng, prefix, str(mask))
        position = rng.randint(0, 7)
        if position == 0:
            statement = "int v%d = %s_take(%s);" % (check_index, p, expression)
        elif position == 1:
            statement = "int v%d = %s_take_two(%s, 7);" % (check_index, p, expression)
        elif position == 2:
            statement = "int v%d = %s_take_two(7, %s);" % (check_index, p, expression)
        elif position == 3:
            statement = "int v%d = %s_take(%s_take(%s));" % (check_index, p, p, expression)
        elif position == 4:
            statement = "%s_Pair pr%d = (%s_Pair){.a = 1, .b = %s}; int v%d = pr%d.b;" % (p, check_index, p, expression, check_index, check_index)
        elif position == 5:
            statement = "%s_Pair pr%d = (%s_Pair){1, %s}; int v%d = pr%d.b;" % (p, check_index, p, expression, check_index, check_index)
        elif position == 6:
            statement = "int* items%d = (int[2]){1, %s}; int v%d = items%d[1];" % (check_index, expression, check_index, check_index)
        else:
            statement = "int v%d = 1 + (%s);" % (check_index, expression)
        body.append("    %s\n" % statement)
        body.append("    sink((u64)(unsigned)v%d);\n" % check_index)
        body.append("    sink((u64)%s_calls * 8u + (u64)%s_conds);\n" % (p, p))
    body.append("    result = hash_state;\n")
    return Unit(globals_text, "".join(body))


# ---------------------------------------------------------------------------
# Family: union_vector
# ---------------------------------------------------------------------------

VECTOR_ELEMENTS = [
    ("signed char", 1, False),
    ("unsigned char", 1, False),
    ("short", 2, False),
    ("unsigned short", 2, False),
    ("int", 4, False),
    ("unsigned int", 4, False),
    ("long long", 8, False),
    ("unsigned long long", 8, False),
    ("float", 4, True),
    ("double", 8, True),
]

VECTOR_BYTES = [16, 32, 64]


def generate_union_vector_unit(rng, unit_index):
    prefix = "uv%d" % unit_index
    element_spelling, element_size, element_is_float = rng.choice(VECTOR_ELEMENTS)
    vector_bytes = rng.choice(VECTOR_BYTES)
    lane_count = vector_bytes // element_size
    vector_type = "%s_V" % prefix
    storage_type = "%s_Storage" % prefix
    globals_parts = []
    globals_parts.append("typedef %s %s __attribute__((vector_size(%d)));\n" % (element_spelling, vector_type, vector_bytes))
    globals_parts.append(
        "typedef union %s\n{\n    %s vector;\n    %s lanes[%d];\n} %s;\n"
        % (storage_type, vector_type, element_spelling, lane_count, storage_type)
    )
    by_value = rng.random() < 0.5
    if by_value:
        globals_parts.append(
            "static %s %s_combine(%s a, %s b)\n{\n    return a + b;\n}\n"
            % (vector_type, prefix, vector_type, vector_type)
        )

    body = []
    # Frame-layout canaries around the vector storage: a union-vector local
    # mis-sized or mis-aligned in the frame historically clobbered neighbours.
    body.append("    unsigned int before_canary = 0x%08Xu;\n" % rng.randrange(1, 1 << 32))
    body.append("    %s a;\n" % storage_type)
    body.append("    unsigned int middle_canary = 0x%08Xu;\n" % rng.randrange(1, 1 << 32))
    body.append("    %s b;\n" % storage_type)
    body.append("    unsigned int after_canary = 0x%08Xu;\n" % rng.randrange(1, 1 << 32))
    values_a = [rng.randint(1, 9) for _ in range(lane_count)]
    values_b = [rng.randint(1, 9) for _ in range(lane_count)]
    body.append("    for (int lane = 0; lane < %d; lane += 1)\n    {\n" % lane_count)
    body.append("        a.lanes[lane] = (%s)((lane * 7 + %d) %% 9 + 1);\n" % (element_spelling, values_a[0]))
    body.append("        b.lanes[lane] = (%s)((lane * 5 + %d) %% 9 + 1);\n" % (element_spelling, values_b[0]))
    body.append("    }\n")
    operations = ["+", "-"]
    if not element_is_float:
        operations += ["&", "|", "^"]
    operations.append("*")
    operator = rng.choice(operations)
    body.append("    %s c;\n" % storage_type)
    if by_value:
        body.append("    c.vector = %s_combine(a.vector %s b.vector, b.vector);\n" % (prefix, operator))
    else:
        body.append("    c.vector = a.vector %s b.vector;\n" % operator)
    if rng.random() < 0.5:
        scalar = rng.randint(1, 4)
        second_operator = rng.choice(["+", "-"])
        body.append("    c.vector = c.vector %s %d;\n" % (second_operator, scalar))
    if rng.random() < 0.4:
        body.append("    c.vector = -c.vector;\n")
    body.append("    u64 folded = 0;\n")
    body.append("    for (int lane = 0; lane < %d; lane += 1)\n    {\n" % lane_count)
    if element_is_float:
        body.append("        folded = folded * 31u + (u64)(long long)c.lanes[lane];\n")
    else:
        body.append("        folded = folded * 31u + (u64)(unsigned long long)c.lanes[lane];\n")
    body.append("    }\n")
    body.append("    sink(folded);\n")
    if rng.random() < 0.5:
        # Through (long long) first: a negative float converted straight to an
        # unsigned type is undefined, and lanes go negative after - and unary -.
        body.append("    sink((u64)(long long)c.vector[%d]);\n" % rng.randrange(lane_count))
    body.append("    sink((u64)before_canary + (u64)middle_canary * 3u + (u64)after_canary * 7u);\n")
    body.append("    sink((u64)sizeof(%s) * 100u + (u64)sizeof(%s));\n" % (vector_type, storage_type))
    body.append("    result = hash_state;\n")
    return Unit("".join(globals_parts), "".join(body))


# ---------------------------------------------------------------------------
# Driving
# ---------------------------------------------------------------------------

FAMILY_GENERATORS = {
    "enum_sizeof": generate_enum_sizeof_unit,
    "array_bound": generate_array_bound_unit,
    "sizeof_expr": generate_sizeof_expr_unit,
    "lazy_operand": generate_lazy_operand_unit,
    "union_vector": generate_union_vector_unit,
}


def generate_program(family, seed, unit_count):
    # zlib.crc32 rather than hash(): the latter is salted per interpreter run,
    # and a seed must reproduce the same program forever.
    rng = random.Random(zlib.crc32(family.encode()) * 0x9E3779B9 + seed)
    generator = FAMILY_GENERATORS[family]
    units = [generator(rng, unit_index) for unit_index in range(unit_count)]
    return Program(family, seed, units)


@dataclass
class Observation:
    label: str
    compile_ok: bool
    compile_output: str
    compile_returncode: int
    run_returncode: int = None
    run_stdout: bytes = b""
    run_timeout: bool = False

    def behavior_key(self):
        return (self.run_returncode, self.run_stdout, self.run_timeout)


def clean_environment():
    environment = dict(os.environ)
    environment["LD_PRELOAD"] = ""
    return environment


def compile_and_run(label, compile_command, source_path, binary_path, work_directory):
    environment = clean_environment()
    command = compile_command + [source_path, "-o", binary_path]
    try:
        compile_process = subprocess.run(
            command, capture_output=True, timeout=COMPILE_TIMEOUT_SECONDS,
            cwd=work_directory, env=environment,
        )
    except subprocess.TimeoutExpired:
        return Observation(label, False, "compile timeout", -9999)
    output = (compile_process.stdout + compile_process.stderr).decode("utf-8", "replace")
    if compile_process.returncode != 0:
        return Observation(label, False, output, compile_process.returncode)
    observation = Observation(label, True, output, 0)
    try:
        run_process = subprocess.run(
            [binary_path], capture_output=True, timeout=RUN_TIMEOUT_SECONDS,
            cwd=work_directory, env=environment,
        )
        observation.run_returncode = run_process.returncode
        observation.run_stdout = run_process.stdout
    except subprocess.TimeoutExpired:
        observation.run_timeout = True
    return observation


@dataclass
class CaseResult:
    family: str
    seed: int
    category: str  # ok | behavior | rejects | ide-crash | run-crash | generator
    detail: str = ""
    observations: list = field(default_factory=list)


def modes(arguments):
    ide_path = os.path.abspath(arguments.ide)
    return [
        ("clang-O0", [arguments.cc, "-O0", "-w"]),
        ("clang-O2", [arguments.cc, "-O2", "-w"]),
        ("ide", [ide_path, "cc"]),
        ("ide-canon", [ide_path, "cc", "-fno-register-allocator"]),
    ]


def evaluate_case(arguments, family, seed, unit_count, work_directory, selected=None):
    program = generate_program(family, seed, unit_count)
    source_text = program.render(selected)
    tag = "%s_%d" % (family, seed)
    if selected is not None:
        tag += "_u" + "_".join(str(index) for index in selected)
    source_path = os.path.join(work_directory, tag + ".c")
    with open(source_path, "w") as source_file:
        source_file.write(source_text)
    observations = []
    for label, compile_command in modes(arguments):
        binary_path = os.path.join(work_directory, tag + "." + label)
        observations.append(compile_and_run(label, compile_command, source_path, binary_path, work_directory))
    result = classify(family, seed, observations)
    return result, source_path, source_text


def classify(family, seed, observations):
    reference, control, ide_fast, ide_canon = observations
    result = CaseResult(family, seed, "ok", observations=observations)
    if not reference.compile_ok or not control.compile_ok:
        result.category = "generator"
        result.detail = "clang rejected the generated program"
    elif reference.run_timeout or control.run_timeout:
        result.category = "generator"
        result.detail = "clang-built binary timed out"
    elif reference.behavior_key() != control.behavior_key():
        result.category = "generator"
        result.detail = "clang -O0 and -O2 disagree (undefined behavior in the generator)"
    else:
        for ide_observation in (ide_fast, ide_canon):
            if not ide_observation.compile_ok:
                if ide_observation.compile_returncode < 0:
                    result.category = "ide-crash"
                    result.detail = "%s: compiler terminated by signal %d" % (ide_observation.label, -ide_observation.compile_returncode)
                else:
                    result.category = "rejects"
                    result.detail = "%s: %s" % (ide_observation.label, ide_observation.compile_output.strip().splitlines()[-1] if ide_observation.compile_output.strip() else "no diagnostic")
            elif ide_observation.run_timeout:
                result.category = "behavior"
                result.detail = "%s: run timed out" % ide_observation.label
            elif ide_observation.behavior_key() != reference.behavior_key():
                if ide_observation.run_returncode is not None and ide_observation.run_returncode < 0:
                    result.category = "run-crash"
                    result.detail = "%s: binary terminated by signal %d" % (ide_observation.label, -ide_observation.run_returncode)
                else:
                    result.category = "behavior"
                    result.detail = "%s: exit/stdout differ" % ide_observation.label
            if result.category != "ok":
                break
    return result


def divergent_units(arguments, family, seed, unit_count, work_directory):
    """Re-run the same seed one unit at a time; returns the divergent indices."""
    indices = []
    for unit_index in range(unit_count):
        result, _, _ = evaluate_case(arguments, family, seed, unit_count, work_directory, selected=[unit_index])
        if result.category != "ok":
            indices.append((unit_index, result.category, result.detail))
    return indices


def write_report(divergence_directory, result, source_text, unit_findings):
    tag = "%s_%d" % (result.family, result.seed)
    os.makedirs(divergence_directory, exist_ok=True)
    with open(os.path.join(divergence_directory, tag + ".c"), "w") as source_file:
        source_file.write(source_text)
    with open(os.path.join(divergence_directory, tag + ".report.txt"), "w") as report_file:
        report_file.write("family=%s seed=%d category=%s\n" % (result.family, result.seed, result.category))
        report_file.write("detail: %s\n\n" % result.detail)
        for observation in result.observations:
            report_file.write("--- %s ---\n" % observation.label)
            report_file.write("compile_ok=%s returncode=%s\n" % (observation.compile_ok, observation.compile_returncode))
            if observation.compile_output.strip():
                report_file.write("compile output:\n%s\n" % observation.compile_output.strip())
            if observation.compile_ok:
                report_file.write("run returncode=%s timeout=%s\n" % (observation.run_returncode, observation.run_timeout))
                report_file.write("stdout:\n%s\n" % observation.run_stdout.decode("utf-8", "replace"))
            report_file.write("\n")
        if unit_findings:
            report_file.write("divergent units (isolated re-runs):\n")
            for unit_index, category, detail in unit_findings:
                report_file.write("  unit %d: %s (%s)\n" % (unit_index, category, detail))


def run_one(arguments, family, seed, work_root, divergence_directory):
    work_directory = os.path.join(work_root, "%s_%d" % (family, seed))
    os.makedirs(work_directory, exist_ok=True)
    result, _, source_text = evaluate_case(arguments, family, seed, arguments.units, work_directory)
    unit_findings = []
    if result.category != "ok":
        unit_findings = divergent_units(arguments, family, seed, arguments.units, work_directory)
        write_report(divergence_directory, result, source_text, unit_findings)
    shutil.rmtree(work_directory, ignore_errors=True)
    return result, unit_findings


def self_test():
    """The generators must be deterministic and must render compilable text."""
    failures = 0
    for family in FAMILY_GENERATORS:
        first = generate_program(family, 42, 4).render()
        second = generate_program(family, 42, 4).render()
        if first != second:
            print("self-test FAIL: %s is not deterministic" % family)
            failures += 1
        if "unit_3" not in first or "int main(void)" not in first:
            print("self-test FAIL: %s render is incomplete" % family)
            failures += 1
        single = generate_program(family, 42, 4).render(selected=[2])
        if "unit_2" not in single or "unit_1" in single:
            print("self-test FAIL: %s unit selection is wrong" % family)
            failures += 1
    print("self-test %s" % ("FAILED" if failures else "passed"))
    return 1 if failures else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--families", default=",".join(FAMILY_GENERATORS), help="comma-separated family list")
    parser.add_argument("--count", type=int, default=100, help="programs per family")
    parser.add_argument("--seed", type=int, default=1, help="first seed; program seeds are seed..seed+count-1")
    parser.add_argument("--units", type=int, default=6, help="units per program")
    parser.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    parser.add_argument("--ide", default=DEFAULT_IDE)
    parser.add_argument("--cc", default="clang")
    parser.add_argument("--isolate", default=None, help="family:seed — print the per-unit verdicts for one seed and keep its sources")
    parser.add_argument("--self-test", action="store_true")
    arguments = parser.parse_args()

    exit_code = 0
    if arguments.self_test:
        exit_code = self_test()
    else:
        os.chdir(REPOSITORY_ROOT)
        if not os.path.exists(arguments.ide):
            print("missing %s — build it with ./build.sh build --config Release -t ide" % arguments.ide)
            exit_code = 1
        else:
            # Absolute: the compile and run subprocesses use the case's work
            # directory as their cwd, where a repository-relative path would
            # not resolve.
            output_root = os.path.abspath(OUTPUT_ROOT)
            work_root = os.path.join(output_root, "work")
            divergence_directory = os.path.join(output_root, "divergences")
            os.makedirs(work_root, exist_ok=True)
            if arguments.isolate:
                family, _, seed_text = arguments.isolate.partition(":")
                seed = int(seed_text)
                isolate_directory = os.path.join(output_root, "isolate_%s_%d" % (family, seed))
                os.makedirs(isolate_directory, exist_ok=True)
                result, source_path, _ = evaluate_case(arguments, family, seed, arguments.units, isolate_directory)
                print("whole program: %s (%s)" % (result.category, result.detail))
                for unit_index, category, detail in divergent_units(arguments, family, seed, arguments.units, isolate_directory):
                    print("unit %d: %s (%s)" % (unit_index, category, detail))
                print("sources kept under %s" % isolate_directory)
            else:
                families = [family.strip() for family in arguments.families.split(",") if family.strip()]
                unknown = [family for family in families if family not in FAMILY_GENERATORS]
                if unknown:
                    print("unknown families: %s" % ", ".join(unknown))
                    exit_code = 1
                else:
                    tasks = [(family, seed) for family in families
                             for seed in range(arguments.seed, arguments.seed + arguments.count)]
                    tallies = {}
                    divergence_count = 0
                    with concurrent.futures.ThreadPoolExecutor(max_workers=arguments.jobs) as pool:
                        futures = {pool.submit(run_one, arguments, family, seed, work_root, divergence_directory): (family, seed)
                                   for family, seed in tasks}
                        completed = 0
                        for future in concurrent.futures.as_completed(futures):
                            family, seed = futures[future]
                            result, unit_findings = future.result()
                            tallies.setdefault(family, {}).setdefault(result.category, 0)
                            tallies[family][result.category] += 1
                            completed += 1
                            if result.category != "ok":
                                divergence_count += 1
                                units_text = ",".join(str(unit_index) for unit_index, _, _ in unit_findings) or "-"
                                print("[%d/%d] %s seed=%d %s units=%s: %s"
                                      % (completed, len(tasks), family, seed, result.category, units_text, result.detail))
                            elif completed % 200 == 0:
                                print("[%d/%d] ..." % (completed, len(tasks)))
                    print("\nsummary (programs per verdict):")
                    for family in families:
                        family_tallies = tallies.get(family, {})
                        row = "  %-13s" % family
                        for category in ("ok", "behavior", "rejects", "ide-crash", "run-crash", "generator"):
                            row += " %s=%-5d" % (category, family_tallies.get(category, 0))
                        print(row)
                    if divergence_count:
                        print("\n%d divergent programs; sources and reports under %s" % (divergence_count, divergence_directory))
                        exit_code = 2
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
