#!/usr/bin/env python3
"""Exercise the admission workflow's exact self-test tree without network I/O."""

from __future__ import annotations

import os
from pathlib import Path
import re
import subprocess
import tempfile
import textwrap
import unittest


ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github/workflows/api-migration-policy.yml"
PREPARE = "Prepare exact admission self-test tree"
TEST = "Test native-retirement merge admission"
TEST_PATHS = (
    "tools/native_retirement_merge_gate_test.py",
    "tools/native_retirement_admission_checkout_test.py",
)


def step(name: str) -> str:
    marker = "      - name: " + name + "\n"
    return WORKFLOW.read_text().split(marker, 1)[1].split("      - name:", 1)[0]


def script(block: str) -> str:
    if "        run: |\n" in block:
        return textwrap.dedent(block.split("        run: |\n", 1)[1])
    return block.split("        run: ", 1)[1].strip() + "\n"


def git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-c", "core.hooksPath=/dev/null", "-C", str(repo), *args],
        text=True, capture_output=True, check=True,
    )
    return result.stdout.strip()


class CheckoutTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.repo = self.root / "candidate"
        git(self.root, "init", "-b", "main", str(self.repo))
        git(self.repo, "config", "user.name", "Test User")
        git(self.repo, "config", "user.email", "test@example.invalid")
        self.write("README.md", "base\n")
        self.write("generated.h", "old generated bytes\n")
        self.ancestor = self.commit("before admission tests existed")
        for path in TEST_PATHS:
            self.write(path, "raise SystemExit(0)\n")
        self.write("generated.h", "current main generated bytes\n")
        self.base = self.commit("introduce admission self-tests on main")
        git(self.repo, "checkout", "-b", "feature", self.ancestor)
        self.write("README.md", "feature\n")
        self.head = self.commit("unrelated older feature")

    def write(self, relative: str, content: str):
        path = self.repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    def commit(self, message: str) -> str:
        git(self.repo, "add", "-A")
        git(self.repo, "commit", "-m", message)
        return git(self.repo, "rev-parse", "HEAD")

    def prepare(self, event: str = "pull_request", **overrides):
        environment = {
            **os.environ,
            "GITHUB_WORKSPACE": str(self.root),
            "EVENT_NAME": event,
            "BASE_SHA": self.base,
            "HEAD_SHA": self.head,
            **overrides,
        }
        return subprocess.run(
            ["bash", "-e", "-o", "pipefail", "-c", script(step(PREPARE))],
            cwd=self.root, env=environment, text=True, capture_output=True,
        )

    def run_self_tests(self):
        block = step(TEST)
        directory = re.search(r"^        working-directory: (.+)$", block, re.M)
        self.assertIsNotNone(directory)
        return subprocess.run(
            ["bash", "-e", "-o", "pipefail", "-c", script(block)],
            cwd=self.root / directory.group(1), text=True, capture_output=True,
        )

    def candidate_state(self):
        return (
            git(self.repo, "rev-parse", "HEAD"),
            git(self.repo, "write-tree"),
            git(self.repo, "status", "--porcelain"),
            git(self.repo, "show-ref", "--heads"),
        )

    def test_older_feature_runs_new_main_tests_without_changing_candidate(self):
        before = self.candidate_state()
        self.assertFalse((self.repo / TEST_PATHS[0]).exists())
        # This case also executes the old workflow unchanged as a negative
        # control: it fails trying to run a file absent on the older head.
        if "      - name: " + PREPARE + "\n" in WORKFLOW.read_text():
            prepared = self.prepare()
            self.assertEqual(prepared.returncode, 0, prepared.stderr)
        result = self.run_self_tests()
        self.assertEqual(result.returncode, 0, result.stderr)
        combined = self.root / "admission-tests"
        expected = git(self.repo, "merge-tree", "--write-tree", self.base, self.head)
        self.assertEqual(git(combined, "write-tree"), expected)
        self.assertEqual((combined / "README.md").read_text(), "feature\n")
        self.assertEqual((combined / "generated.h").read_text(), "current main generated bytes\n")
        self.assertEqual(self.candidate_state(), before)
        self.assertFalse((self.repo / TEST_PATHS[0]).exists())

    def test_candidate_self_test_failure_is_not_hidden_by_trusted_copy(self):
        git(self.repo, "checkout", "-B", "feature", self.base)
        self.write(TEST_PATHS[0], "raise SystemExit(23)\n")
        self.head = self.commit("candidate changes a self-test")
        prepared = self.prepare()
        self.assertEqual(prepared.returncode, 0, prepared.stderr)
        result = self.run_self_tests()
        self.assertEqual(result.returncode, 23, result.stderr)

    def test_deleted_self_tests_fail_closed(self):
        for path in TEST_PATHS:
            with self.subTest(path=path):
                git(self.repo, "checkout", "-B", "feature", self.base)
                (self.repo / path).unlink()
                self.head = self.commit("delete " + path)
                before = self.candidate_state()
                result = self.prepare()
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(self.candidate_state(), before)
                if (self.root / "admission-tests").exists():
                    git(self.repo, "worktree", "remove", "--force", str(self.root / "admission-tests"))

    def test_conflicting_source_fails_without_changing_candidate(self):
        git(self.repo, "checkout", "main")
        self.write("README.md", "new main conflicting text\n")
        self.base = self.commit("conflicting main change")
        git(self.repo, "checkout", "feature")
        before = self.candidate_state()
        result = self.prepare()
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(self.candidate_state(), before)
        self.assertFalse((self.root / "admission-tests").exists())

    def test_push_dispatch_and_merge_group_use_exact_existing_head(self):
        git(self.repo, "checkout", "-B", "feature", self.base)
        self.write("README.md", "already integrated candidate\n")
        self.head = self.commit("exact non-PR head")
        for event in ("push", "workflow_dispatch", "merge_group"):
            with self.subTest(event=event):
                before = self.candidate_state()
                prepared = self.prepare(event)
                self.assertEqual(prepared.returncode, 0, prepared.stderr)
                combined = self.root / "admission-tests"
                self.assertEqual(git(combined, "write-tree"), git(self.repo, "rev-parse", self.head + "^{tree}"))
                result = self.run_self_tests()
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(self.candidate_state(), before)
                git(self.repo, "worktree", "remove", "--force", str(combined))

    def test_wrong_head_and_invalid_identities_fail_closed(self):
        for identities in ({"HEAD_SHA": self.base}, {"HEAD_SHA": "HEAD"}, {"BASE_SHA": "main"}):
            with self.subTest(identities=identities):
                before = self.candidate_state()
                result = self.prepare(**identities)
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(self.candidate_state(), before)
                self.assertFalse((self.root / "admission-tests").exists())

    def test_unknown_event_fails_closed(self):
        before = self.candidate_state()
        result = self.prepare("issue_comment")
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(self.candidate_state(), before)
        self.assertFalse((self.root / "admission-tests").exists())

    def test_validation_tree_does_not_replace_admission_authority(self):
        enforcement = step("Enforce trusted native-retirement integration")
        self.assertIn('tool="$GITHUB_WORKSPACE/trusted/tools/native_retirement_merge_gate.py"', enforcement)
        self.assertIn('--repo-root "$GITHUB_WORKSPACE/candidate"', enforcement)
        self.assertIn('--base "$BASE_SHA"', enforcement)
        self.assertIn('--head "$HEAD_SHA"', enforcement)
        self.assertIn('--current-main "$current_main"', enforcement)
        self.assertNotIn("admission-tests", enforcement)
        self.assertNotIn("--allow-pending", enforcement)
        block = step(TEST)
        self.assertIn("working-directory: admission-tests", block)
        for path in TEST_PATHS:
            self.assertIn("python3 -B " + path + " -v", script(block))
        self.assertNotIn("continue-on-error", block)
        self.assertNotIn("|| true", script(block))


if __name__ == "__main__":
    unittest.main()
