# SDK graph inputs for APK packaging. Numeric API/build-tools versions use
# CMake's version comparison (available before the 3.17 minimum). Prefer the
# newest stable build-tools; use alpha/beta/rc previews only without a stable.
function(buster_android_build_tools output sdk override)
    set(selected "${override}")
    if (selected)
        if (NOT IS_DIRECTORY "${selected}")
            message(FATAL_ERROR "BUSTER_ANDROID_BUILD_TOOLS_DIR is not an installed directory: ${selected}")
        endif()
    else()
        file(GLOB candidates LIST_DIRECTORIES TRUE "${sdk}/build-tools/*")
        set(best_version "")
        set(best_stage -1)
        set(best_preview 0)
        foreach(candidate IN LISTS candidates)
            get_filename_component(version "${candidate}" NAME)
            if (IS_DIRECTORY "${candidate}" AND version MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(alpha|beta|rc)([0-9]+))?$")
                set(numeric_version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
                set(stage_name "${CMAKE_MATCH_5}")
                set(preview "${CMAKE_MATCH_6}")
                set(stage 3)
                if (stage_name STREQUAL "alpha")
                    set(stage 0)
                elseif (stage_name STREQUAL "beta")
                    set(stage 1)
                elseif (stage_name STREQUAL "rc")
                    set(stage 2)
                else()
                    set(preview 0)
                endif()
                set(newest OFF)
                if (NOT selected OR (stage EQUAL 3 AND NOT best_stage EQUAL 3))
                    set(newest ON)
                elseif ((stage EQUAL 3 AND best_stage EQUAL 3) OR (NOT stage EQUAL 3 AND NOT best_stage EQUAL 3))
                    if (numeric_version VERSION_GREATER best_version)
                        set(newest ON)
                    elseif (numeric_version VERSION_EQUAL best_version)
                        if (stage GREATER best_stage OR (stage EQUAL best_stage AND preview GREATER best_preview))
                            set(newest ON)
                        endif()
                    endif()
                endif()
                if (newest)
                    set(selected "${candidate}")
                    set(best_version "${numeric_version}")
                    set(best_stage "${stage}")
                    set(best_preview "${preview}")
                endif()
            endif()
        endforeach()
        if (NOT selected)
            message(FATAL_ERROR "No valid Android build-tools version directory under ${sdk}/build-tools; install stable major.minor.patch tools or set BUSTER_ANDROID_BUILD_TOOLS_DIR")
        endif()
    endif()
    set(${output} "${selected}" PARENT_SCOPE)
endfunction()

function(buster_android_platform_jar output sdk platform override)
    set(selected "${override}")
    if (selected)
        if (NOT EXISTS "${selected}" OR IS_DIRECTORY "${selected}")
            message(FATAL_ERROR "BUSTER_ANDROID_JAR is not an installed android.jar: ${selected}")
        endif()
    else()
        if (platform MATCHES "^(android-)?([0-9]+)$")
            set(requested "${sdk}/platforms/android-${CMAKE_MATCH_2}/android.jar")
            if (EXISTS "${requested}" AND NOT IS_DIRECTORY "${requested}")
                set(selected "${requested}")
            endif()
        endif()
        if (NOT selected)
            file(GLOB candidates "${sdk}/platforms/*/android.jar")
            set(best_api 0)
            foreach(candidate IN LISTS candidates)
                get_filename_component(directory "${candidate}" DIRECTORY)
                get_filename_component(name "${directory}" NAME)
                if (NOT IS_DIRECTORY "${candidate}" AND name MATCHES "^android-([0-9]+)$")
                    set(api "${CMAKE_MATCH_1}")
                    if (api VERSION_GREATER best_api)
                        set(selected "${candidate}")
                        set(best_api "${api}")
                    endif()
                endif()
            endforeach()
        endif()
        if (NOT selected)
            message(FATAL_ERROR "No valid android.jar under ${sdk}/platforms/android-<API>; install an Android SDK platform or set BUSTER_ANDROID_JAR")
        endif()
    endif()
    set(${output} "${selected}" PARENT_SCOPE)
endfunction()
