if (NOT DEFINED BUSTER_D3D12_VERTEX_INPUT)
    message(FATAL_ERROR "BUSTER_D3D12_VERTEX_INPUT is required")
endif()
if (NOT DEFINED BUSTER_D3D12_PIXEL_INPUT)
    message(FATAL_ERROR "BUSTER_D3D12_PIXEL_INPUT is required")
endif()
if (NOT DEFINED BUSTER_D3D12_HEADER_OUTPUT)
    message(FATAL_ERROR "BUSTER_D3D12_HEADER_OUTPUT is required")
endif()

function(buster_read_hlsl_source out_var input)
    file(READ "${input}" source)
    string(REPLACE "\\" "\\\\" source "${source}")
    string(REPLACE "\"" "\\\"" source "${source}")
    string(REPLACE "
" "\\n\" \\\n\"" source "${source}")
    set(${out_var} "${source}" PARENT_SCOPE)
endfunction()

buster_read_hlsl_source(vertex_source "${BUSTER_D3D12_VERTEX_INPUT}")
buster_read_hlsl_source(pixel_source "${BUSTER_D3D12_PIXEL_INPUT}")

get_filename_component(output_dir "${BUSTER_D3D12_HEADER_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${BUSTER_D3D12_HEADER_OUTPUT}"
"/* Generated by CMake. Do not edit. */\n"
"#ifndef BUSTER_SHADERS_D3D12_H\n"
"#define BUSTER_SHADERS_D3D12_H\n"
"\n"
"#define BUSTER_SHADER_RECT_D3D12_VERTEX_SOURCE \"${vertex_source}\"\n"
"#define BUSTER_SHADER_RECT_D3D12_PIXEL_SOURCE \"${pixel_source}\"\n"
"\n"
"#endif /* BUSTER_SHADERS_D3D12_H */\n"
)
