if (NOT DEFINED BUSTER_METAL_VERTEX_INPUT)
    message(FATAL_ERROR "BUSTER_METAL_VERTEX_INPUT is required")
endif()
if (NOT DEFINED BUSTER_METAL_FRAGMENT_INPUT)
    message(FATAL_ERROR "BUSTER_METAL_FRAGMENT_INPUT is required")
endif()
if (NOT DEFINED BUSTER_METAL_HEADER_OUTPUT)
    message(FATAL_ERROR "BUSTER_METAL_HEADER_OUTPUT is required")
endif()

function(buster_read_metal_source out_var input)
    file(READ "${input}" source)
    # Slang's Metal backend emits texture-array entry parameters without the
    # Metal resource attribute. The runtime binds the array starting at texture(0),
    # matching the old hand-written MSL, so add that attribute before embedding.
    string(REGEX REPLACE "(array<texture2d<float, access::sample>, int\\([0-9]+\\)> textures_[0-9]+)(, sampler texture_sampler_[0-9]+ \\[\\[sampler\\(0\\)\\]\\])" "\\1 [[texture(0)]]\\2" source "${source}")
    string(REPLACE "\\" "\\\\" source "${source}")
    string(REPLACE "\"" "\\\"" source "${source}")
    string(REPLACE "
" "\\n\" \\\n\"" source "${source}")
    set(${out_var} "${source}" PARENT_SCOPE)
endfunction()

buster_read_metal_source(vertex_source "${BUSTER_METAL_VERTEX_INPUT}")
buster_read_metal_source(fragment_source "${BUSTER_METAL_FRAGMENT_INPUT}")

get_filename_component(output_dir "${BUSTER_METAL_HEADER_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${BUSTER_METAL_HEADER_OUTPUT}"
"/* Generated by CMake. Do not edit. */\n"
"#ifndef BUSTER_SHADERS_METAL_H\n"
"#define BUSTER_SHADERS_METAL_H\n"
"\n"
"#define BUSTER_SHADER_RECT_METAL_VERTEX_SOURCE \"${vertex_source}\"\n"
"#define BUSTER_SHADER_RECT_METAL_FRAGMENT_SOURCE \"${fragment_source}\"\n"
"\n"
"#endif /* BUSTER_SHADERS_METAL_H */\n"
)
