# Effective build architecture: Apple -arch requests override CMake's host
# processor. One architecture owns each source graph; universal graphs are
# rejected before a host module or native tuning can leak into another slice.
function(buster_architecture_normalize output processor)
    string(TOLOWER "${processor}" normalized)
    if (normalized MATCHES "^(amd64|x86-64|x86_64)$")
        set(normalized x86_64)
    elseif (normalized MATCHES "^(aarch64|arm64|a64)$")
        set(normalized arm64)
    endif()
    set(${output} "${normalized}" PARENT_SCOPE)
endfunction()

function(buster_target_architecture output_processor output_cross system processor host osx_architectures cross)
    set(target "${processor}")
    if (system STREQUAL "Darwin" OR system STREQUAL "iOS")
        if (osx_architectures)
            list(LENGTH osx_architectures architecture_count)
            if (NOT architecture_count EQUAL 1)
                message(FATAL_ERROR "Buster requires one CMAKE_OSX_ARCHITECTURES entry; universal Apple builds are unsupported: ${osx_architectures}")
            endif()
            list(GET osx_architectures 0 target)
        elseif (NOT target)
            set(target "${host}")
        endif()
        buster_architecture_normalize(target "${target}")
        buster_architecture_normalize(normalized_host "${host}")
        if (NOT target MATCHES "^(x86_64|arm64)$")
            message(FATAL_ERROR "Unsupported Buster Apple target architecture: ${target}; use arm64 or x86_64")
        endif()
        if (NOT target STREQUAL normalized_host)
            set(cross ON)
        endif()
    elseif (NOT target)
        set(target "${host}")
    endif()
    set(${output_processor} "${target}" PARENT_SCOPE)
    set(${output_cross} "${cross}" PARENT_SCOPE)
endfunction()
